id: P001677
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17371
  title: བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱིས་མཛད་པའི་ཀླུ་གཏོར།
  author: ''
  volumes:
    a8849f1c128742729f0d5e4b67e34364:
      image_group_id: I8LS17377
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
